# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iOSReactTest3' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for iOSReactTest3
  pod 'MobileCenter/MobileCenterPush', '~> 0.9.0'
  pod 'RNMobileCenter', '~> 0.5.0'
  pod 'MobileCenter', '~> 0.9.0'

  

  target 'iOSReactTest3Tests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'iOSReactTest3-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for iOSReactTest3-tvOS

  target 'iOSReactTest3-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
